### ISSUE TITLE
Output binding shall allow to execute Stored Procedure (like input binding)

### ISSUE THREAD

**Issue by petr-hollay** [Azure/azure-functions-sql-extension#658] opened 2023-02-03 13:40 UTC
**Expected behavior**
Output binding for compiled C# shall allow to execute Stored Procedure (like input binding) for inserting and updating the data in Azure SQL.
Output binding shall then allow to execute the updates using stored procedure by flushing the async collector from within the Azure Functions code.

Example of input binding: [azure-functions-sql-extension/GetProductsStoredProcedure.cs at main · Azure/azure-functions-sql-extension (github.com)](https://github.com/Azure/azure-functions-sql-extension/blob/main/samples/samples-csharp/InputBindingSamples/GetProductsStoredProcedure.cs)

**Actual behavior**
Data in Azure SQL DB cannot be updated using stored procedure.

**Known workarounds**
Go around the standard output binding and use Azure SQL SDK directly.

**Related information**
Different but related issue: #605

**Comment by Charles-Gagnon** [comment] 2023-02-03 17:58
Closing as a duplicate of https://github.com/Azure/azure-functions-sql-extension/issues/605 - the root ask is the same as that one (I updated the title there to reflect that)

**Closed by Charles-Gagnon** 2023-02-03 17:58 UTC
