### ISSUE TITLE
support TRACK_COLUMNS_UPDATED

### ISSUE THREAD

**Issue by waynebrantley** [Azure/azure-functions-sql-extension#1156] opened 2024-12-06 04:49 UTC
Add support for TRACK_COLUMNS_UPDATED.

Currently this is implemented to take the primary key data in the change tracking table and use that to return the 'rows' that change so we can take action on them.

It would be nice to know what columns changed so we can decided if such action is necessary.   SQL Server supports this with the TRACK_COLUMNS_UPDATED feature.

Expose this data (if sql server feature is enabled) in the SQL Trigger.

https://learn.microsoft.com/en-us/sql/relational-databases/track-changes/enable-and-disable-change-tracking-sql-server?view=sql-server-ver16#enable-change-tracking-for-a-table

**Comment by VasuBhog** [comment] 2024-12-10 21:37
Hi @waynebrantley, this is a duplicate of https://github.com/Azure/azure-functions-sql-extension/issues/710. Please upvote and discuss the issue there.

**Closed by VasuBhog** 2024-12-10 21:37 UTC
Labels: enhancement, Triage: Done
